# Jekyll Configuration

url: http://www.bitspin.org
title: "::bitspin.org"
description: Home of c0ding n3rds
author: by Shirk
email: shirk (at) bitspin (dot) org
analytics_id: #Google Analytics ID : UA-xxx-xxx  

auto: false
lsi: false
pygments: true
server_port: 4000
markdown: maruku

maruku:
  use_tex: false
  use_divs: false
  png_dir: img/tex
  png_url: /img/tex
